name: Deploy to Lightsail Container Service
run-name: Deploy ${{ github.ref_name }} to ${{ inputs.deployment_target }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Deployment target'
        required: true
        default: 'dev1'
        type: choice
        options:
          - dev1
          - prd
          - demo

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    environment:
      name: ${{ inputs.deployment_target }}
    env:
      APP_NAME: awesome
      LCS_SERVICE: awesome-${{ inputs.deployment_target }}
      LCS_CONTAINER: awesome-wp
      AWS_REGION: ap-southeast-1
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create valid tag name
        id: create-tag-name
        run: |
          TAG_NAME="${GITHUB_REF_NAME//\//-}"    
          TAG_NAME="${TAG_NAME//_/-}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Set Environment Variables
        run: |
          IMAGE_TAG="${{ steps.create-tag-name.outputs.tag_name }}-${{ github.run_number }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "ENVIRONMENT=$(echo ${{ inputs.deployment_target }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
      
      - name: Install Lightsail CLI Plugin
        run: |
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
      
      - name: Retrieve secrets from SSM Parameter Store
        id: get-ssm-secrets
        run: |
          # Fetch all parameters under the path
          PARAMS=$(aws ssm get-parameters-by-path \
            --path "/${{ env.APP_NAME }}/${{ inputs.deployment_target }}/" \
            --with-decryption \
            --query "Parameters[].{Key:Name,Val:Value}" \
            --output text)
          
          while read -r full_key value; do
            key=$(basename "$full_key")

            # Mask sensitive values
            if [[ "$key" =~ PASSWORD|PASS|KEY|USER|HOST|AUTH|SALT ]]; then
              echo "::add-mask::$value"
            fi

            # Export to environment
            echo "$key=$value" >> $GITHUB_ENV

          done <<< "$PARAMS"

      - name: Generate htpasswd hash 
        id: htpasswd-hash
        run: |
          AUTH_LINE=$(htpasswd -nb "$BASIC_AUTH_USER" "$BASIC_AUTH_PASSWORD")
          BASIC_AUTH_HASH="${AUTH_LINE#*:}"

          echo "::add-mask::$BASIC_AUTH_HASH"
          echo "BASIC_AUTH_PASSWORD=$BASIC_AUTH_HASH" >> $GITHUB_ENV
          
      - name: Build Docker Image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.LCS_SERVICE }}:${{ env.IMAGE_TAG }}"
          docker build \
            --build-arg ENV=${{ inputs.deployment_target }} \
            --build-arg FQDN=${{ vars.DOMAIN }} \
            --build-arg BASIC_AUTH_USER=$BASIC_AUTH_USER \
            --build-arg BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD \
            -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Create container.json
        run: |
          echo "Using IMAGE_URI: $IMAGE_URI"
          cat <<EOF > container.json
          {
            "containers": {
              "${{ env.LCS_CONTAINER }}": {
                "image": "$IMAGE_URI",
                "ports": {
                  "80": "HTTP"
                },
                "environment": {
                  "DB_PASS": "${{ env.DB_PASSWORD }}",
                  "DB_USER": "${{ env.DB_USER }}",
                  "DB_NAME": "${{ env.DB_NAME }}",
                  "DB_HOST": "${{ env.DB_HOST }}",
                  "AUTH_KEY": "${{ env.AUTH_KEY }}",
                  "AUTH_SALT": "${{ env.AUTH_SALT }}",
                  "LOGGED_IN_KEY": "${{ env.LOGGED_IN_KEY }}",
                  "LOGGED_IN_SALT": "${{ env.LOGGED_IN_SALT }}",
                  "NONCE_KEY": "${{ env.NONCE_KEY }}",
                  "NONCE_SALT": "${{ env.NONCE_SALT }}",
                  "SECURE_AUTH_KEY": "${{ env.SECURE_AUTH_KEY }}",
                  "SECURE_AUTH_SALT": "${{ env.SECURE_AUTH_SALT }}",
                  "WPMS_SMTP_HOST": "${{ env.WPMS_SMTP_HOST }}",
                  "WPMS_SMTP_PASS": "${{ env.WPMS_SMTP_PASS }}",
                  "WPMS_SMTP_PORT": "${{ env.WPMS_SMTP_PORT }}",
                  "WPMS_SMTP_USER": "${{ env.WPMS_SMTP_USER }}",
                  "WP_ENV": "${{ env.WP_ENV }}",
                  "WP_HOME": "${{ env.WP_HOME }}",
                  "WP_SITEURL": "${{ env.WP_SITEURL }}",
                  "RECAPTCHA_SECRET_KEY": "${{ env.RECAPTCHA_SECRET_KEY }}",
                  "RECAPTCHA_SITE_KEY": "${{ env.RECAPTCHA_SITE_KEY }}",
                  "ASSETS_URL": "${{ env.ASSETS_URL }}",
                  "DOMAIN": "${{ vars.DOMAIN }}"
                }
              }
            },
            "publicEndpoint": {
              "containerName": "${{ env.LCS_CONTAINER }}",
              "containerPort": 80
            }
          }
          EOF
          
      - name: Deploy to Lightsail Container Service
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ env.LCS_SERVICE }} \
            --cli-input-json file://container.json

